# Generated by Django 4.0.2 on 2022-02-26 03:29

from django.db import migrations, models
import when2eat.models


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuisine',
            field=models.CharField(default='American', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=when2eat.models.generate_code, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
