# Generated by Django 4.0.2 on 2022-02-26 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0002_user_cuisine_alter_room_code_delete_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_day_length',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 2, 26)),
            preserve_default=False,
        ),
    ]
