# Generated by Django 4.0.2 on 2022-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0003_room_max_day_length_room_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_day_length',
        ),
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(default='2022-02-26'),
            preserve_default=False,
        ),
    ]
