# Generated by Django 4.0.2 on 2022-02-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0004_remove_room_max_day_length_room_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meal',
            field=models.CharField(default='Dinner', max_length=10),
            preserve_default=False,
        ),
    ]
