# Generated by Django 4.0.2 on 2022-02-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0005_room_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='meal',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='when2eat.user')),
            ],
        ),
    ]
