# Generated by Django 4.0.2 on 2022-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0006_alter_room_meal_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_time',
            field=models.TimeField(default='10:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.TimeField(default='10:10'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DateTime',
        ),
    ]
