# Generated by Django 4.0.2 on 2022-02-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('when2eat', '0007_user_end_time_user_start_time_delete_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='end_date',
        ),
    ]
